const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { fingerprint } = require('../api/_lib/normalization-analysis.cjs')
const manifest = require('../scripts/reconciliation-decisions-20260909.json')
const { BACKUP_KEY, EXPECTED_MANIFEST } = require('../scripts/apply-confirmed-reconciliation.cjs')

test('application script is pinned to the reviewed manifest and a unique backup', () => {
  assert.equal(fingerprint(manifest), EXPECTED_MANIFEST)
  assert.equal(BACKUP_KEY, 'backup_confirmed_reconciliation_20260909')
  const source = fs.readFileSync(path.join(__dirname, '../api/_lib/reconciliation-application.cjs'), 'utf8')
  assert.match(source, /state_revision' for update/)
  assert.match(source, /pignus_agendas where id = 'current' for update/)
  assert.match(source, /pignus_work_history where id in[\s\S]*for update/)
  assert.match(source, /existingBackup\.length/)
  assert.match(source, /result\.state\.history\.length !== state\.history\.length/)
  assert.doesNotMatch(source, /delete from pignus_work_history|delete from pignus_agendas/)
})
