const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')
const css = read('src/mobile-layout.css')
test('mobile overrides load after shared modal styles and stay within mobile breakpoints', () => {
  const main = read('src/main.jsx')
  assert.ok(main.indexOf("import './mobile-layout.css'") > main.indexOf("import './components/ui/modal-chrome.css'"))
  assert.equal((css.match(/@media/g) || []).length, 2)
  assert.match(css, /@media \(max-width: 700px\)/)
  assert.match(css, /@media \(max-width: 640px\)/)
})
test('search navigation stays in compact columns with accessible touch targets', () => {
  assert.match(css, /grid-template-columns: minmax\(0, 1fr\) 44px 44px/)
  assert.match(css, /\.weekly-service-search > label \{ grid-column: 1 \/ -1; flex: none/)
  assert.match(css, /min-height: 44px/)
})
test('history and modal controls use available width without reversing action order', () => {
  assert.match(css, /\.history-client \{\s*grid-column: 1 \/ -1 !important/)
  assert.match(css, /\.history-date-filters[\s\S]*repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(css, /flex-direction: row; flex-wrap: wrap/)
  assert.doesNotMatch(css, /flex-direction:\s*column-reverse/)
})
